baseURL = 'https://fspv.github.io/homepage/'
languageCode = 'en-us'
title = 'Pavel Safronov - Software Engineer'

[params]
  description = "Personal website of Pavel Safronov, Software Engineer"
  author = "Pavel Safronov"

# RSS Configuration
rssLimit = 10
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[permalinks]
  posts = "/:year/:month/:slug/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
