name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.123.7
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
  validate-deployed-rss:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install feedparser
        run: pip install feedparser
        
      - name: Wait for deployment to propagate
        run: sleep 30
        
      - name: Check page accessibility
        run: |
          echo "Checking page accessibility..."
          
          # Get the base URL from the repository name
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          SITE_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${REPO_NAME}"
          
          echo "Site URL: $SITE_URL"
          
          # Check main page
          echo "Checking main page..."
          if curl -f -s -o /dev/null "$SITE_URL/"; then
            echo "✓ Main page (/) returns 200"
          else
            echo "✗ Main page (/) failed"
            exit 1
          fi
          
          # Check posts page
          echo "Checking posts page..."
          if curl -f -s -o /dev/null "$SITE_URL/posts/"; then
            echo "✓ Posts page (/posts/) returns 200"
          else
            echo "✗ Posts page (/posts/) failed"
            exit 1
          fi
          
          echo "All pages are accessible!"
          
      - name: Validate deployed RSS feeds
        run: |
          echo "Validating RSS feeds from deployed site..."
          
          # Get the base URL from the repository name
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          SITE_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${REPO_NAME}"
          
          echo "Site URL: $SITE_URL"
          
          # Validate the main RSS feed
          python validate_rss.py "$SITE_URL/index.xml"
          
          # Also validate posts RSS feed
          python validate_rss.py "$SITE_URL/posts/index.xml"
          
          echo "Post-deployment RSS validation completed!"