name: Markdown Format Check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  markdown-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Prettier
      run: npm install -g prettier
      
    - name: Check Markdown formatting
      run: |
        find . -name "*.md" -not -path "./.git/*" -print0 | \
        xargs -0 prettier --parser=markdown --check