name: Validate RSS Feeds

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  validate-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true
        
    - name: Build site
      run: hugo
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install validation tools
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils
        pip install feedparser
        
    - name: Validate XML syntax
      run: |
        echo "Validating XML syntax..."
        
        # Find all XML files in public directory
        find public -name "*.xml" -type f | while read -r xml_file; do
          echo "Checking XML syntax: $xml_file"
          xmllint --noout "$xml_file" || exit 1
        done
        
        echo "All XML files are well-formed!"
        
    - name: Validate RSS 2.0 compliance
      run: |
        echo "Validating RSS 2.0 compliance..."
        python validate_rss.py public